#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    c=0;
    d=0;
    e=0;
    for i in range(0,len(arr)):
        if(arr[i]>0):
            c=c+1;
        if(arr[i]<0):
            d=d+1;
        if(arr[i]==0):
            e=e+1;
    print("{:.6f}".format(c/len(arr)))
    print("{:.6f}".format(d/len(arr)))
    print("{:.6f}".format(e/len(arr)))
        
if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
